name: Print date
run-name: Printing the date

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: date
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Print date
        run: "Get-Date"
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Print date
        run: date
  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    needs:
      - job1
      - job2
      - job3
    steps:
      - name: Print date
        run: date
