name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello world
        run: |
          echo "Add other actions to build",
          echo "test, and deploy your project".
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye world
        run: echo "Goodbye world"
        shell: bash
